<?php
use App\Http\Controllers\Admin\Menu;

return[
    'menu_detail' => [
        [
            'type' => 'item',
            'title' => '主控台',
            'func_name' => 'dashboard',
            'icon' => 'fas fa-tachometer-alt',
            'permission' => 'admin area',
            'controller' => Menu\DashboardController::class,
        ],
        [
            'type' => 'header',
            'title' => '訂單相關功能區塊',
            'func_name' => '',
            'icon' => '',
            'permission' => '',
            'controller' => '',
        ],
        [
            'type' => 'item',
            'title' => '訂單資料',
            'func_name' => 'order',
            'icon' => 'fas fa-shopping-cart',
            'permission' => 'admin order',
            'controller' => Menu\OrderController::class,
            'children'=>[
                [
                    'type' => 'item',
                    'title' => '訂單裝箱列表',
                    'func_name' => 'order-boxing',
                    'icon' => 'fas fa-boxes',
                    'permission' => 'admin order boxing',
                    'controller' => Menu\OrderBoxingController::class,
                ],
                [
                    'type' => 'item',
                    'title' => '訂單列表明細',
                    'func_name' => 'order-detail',
                    'icon' => 'fas fa-box-open',
                    'permission' => 'admin order detail',
                    'controller' => Menu\OrderDetailController::class,
                ],
            ],
        ],
        [
            'type' => 'item',
            'title' => '船班設定功能',
            'func_name' => 'sailing-schedule',
            'icon' => 'fas fa-ship',
            'permission' => 'admin sailing schedule',
            'controller' => Menu\SailingScheduleController::class,
        ],
        [
            'type' => 'item',
            'title' => '帳務管理功能',
            'func_name' => 'payment',
            'icon' => 'fas fa-cash-register',
            'permission' => 'admin payment',
            'controller' => Menu\PaymentController::class,
        ],
        [
            'type' => 'header',
            'title' => '網站管理',
            'func_name' => '',
            'icon' => '',
            'permission' => '',
            'controller' => '',
        ],
        [
            'type' => 'item',
            'title' => '國家資料設定',
            'func_name' => 'country',
            'icon' => 'fas fa-globe',
            'permission' => 'admin country',
            'controller' => Menu\CountryController::class,
        ],
        [
            'type' => 'item',
            'title' => '倉庫資料設定',
            'func_name' => 'warehouse',
            'icon' => 'fas fa-warehouse',
            'permission' => 'admin warehouse',
            'controller' => Menu\WarehouseController::class,
        ],
        [
            'type' => 'header',
            'title' => '後台管理',
            'func_name' => '',
            'icon' => '',
            'permission' => '',
            'controller' => '',
        ],
        [
            'type' => 'item',
            'title' => '會員管理',
            'func_name' => 'user',
            'icon' => 'fas fa-user',
            'permission' => 'admin user',
            'controller' => Menu\UsersController::class,
        ],
        [
            'type' => 'item',
            'title' => '權限管理',
            'func_name' => 'permission',
            'icon' => 'fas fa-lock',
            'permission' => 'admin permission',
            'controller' => Menu\PermissionsController::class,
        ],
        [
            'type' => 'item',
            'title' => '網站資訊&設定',
            'func_name' => 'web-setting',
            'icon' => 'fas fa-cogs',
            'permission' => 'admin web setting',
            'controller' => Menu\WebSettingController::class,
            'children'=>[
                [
                    'type' => 'item',
                    'title' => '一般設定',
                    'func_name' => 'option',
                    'icon' => 'fas fa-key',
                    'permission' => 'admin option',
                    'controller' => Menu\OptionsController::class,
                ],
                [
                    'type' => 'item',
                    'title' => '路由列表',
                    'func_name' => 'route-list',
                    'icon' => 'fas fa-sitemap',
                    'permission' => 'admin route list',
                    'controller' => Menu\RouteListController::class,
                ],
                [
                    'type' => 'item',
                    'title' => '操作紀錄',
                    'func_name' => 'website-log-history',
                    'icon' => 'fas fa-history ',
                    'permission' => 'admin web log',
                    'controller' => Menu\WebLogController::class,
                ],
            ],
        ],
    ],
];
